name: Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main
          folder: .
          target-folder: /geo-movc
