name: Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main # The branch the action should deploy to.
          folder: /geo-movc # The folder the action should deploy.
